### ISSUE TITLE
Quantrabbit -Customer Service Agent city job is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#10]
STEPT TO REPRODUCE:
1. access shaqodoon.ro
2. click on Companii
3. scroll and click on Quantrabbit 
4. look for Customer Service Agent job

EXPECTED RESULT:
city should be Cluj-Napoca

ACTUAL RESULT:
city displayed is Cluj

**Comment by sebiboga** [comment]
@Ioana881 I updated the crawler; re-run the script; please retest; if happy with results, then please CLOSE the bug.
Thank you

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
