### ISSUE TITLE
VMware company card is not redirecting correctly

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_crawlers#100]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. click on Companii
 3. scroll down and click on VMware

EXPECTED RESULTS:
WMware careers page is displayed. (https://careers.vmware.com/main/jobs?page=1)

ACTUAL RESULTS:
A JSON file is displayed.

**Comment by sebiboga** [comment]
@tonisfr I think I fixed the bug. PLEASE RETEST

**Comment by tonisfr** [comment]
retested on PROD environment
the issue was fixed
closing the bug
