### ISSUE TITLE
MediaGalaxy-Consultant Vanzari Orange Store city job is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#11]
STEPS TO RERPODUCE:
1. access shaqodoon.ro
2. click on Companii
3. scroll and click on MediaGalaxy
4. look for Consultant Vanzari Orange Store job

EXPECTED RESULT:
city should be București 

ACTUAL RESULT:
city displayed is Bucuresti

**Comment by sebiboga** [comment]
@Ioana881 fixed the issue; please retest

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
