### ISSUE TITLE
Sage Intacct - null for city

### ISSUE THREAD

**Issue by sebiboga** [sebiboga/shaqo_doon_crawlers#12]
![image](https://user-images.githubusercontent.com/41440889/106386404-7c580e80-63dd-11eb-9a9c-1a1c8e0198b6.png)

https://shaqodoon.ro/jobs/Sage-Intacct

**Comment by sebiboga** [comment]
@Ioana881 fixed. please retest

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
