### ISSUE TITLE
Farmec-Preparator detergenti si produse de curatenie job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#16]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser 
2. Click on Companii
3. Scroll and click on Farmec
4. Look for Preparator detergenti si produse de curatenie job

EXPECTED RESULTS:
city should be Cluj-Napoca

ACTUAL RESULTS:
city displayed is Napoca

**Comment by sebiboga** [comment]
fixed; @Ioana881 please retest

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
