### ISSUE TITLE
Farmec - Agent de vanzari- Consumuri colective job city is not displayed correctly 

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#17]
ENVIRONMENT: PROD 
URL: https://shaqodoon.ro/
browser: Chrome

STEPT TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click on Farmec
4. Look for Agent de vanzari- Consumuri colective job

EXPECTED RESULTS:
city should be Brașov

ACTUAL RESULTS:
city displayed is Brasov

**Comment by sebiboga** [comment]
fixed; @Ioana881 please retest

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
