### ISSUE TITLE
eMAG- Android Developer ( Tazz Team) job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#18]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click in eMAG
4. Look for Androiod Developer ( Tazz Team) job

EXPECTED RESULTS:
city should be Timișoara

ACTUAL RESULTS:
city displayed is Timisoara

**Comment by sebiboga** [comment]
fixed; @Ioana881 please retest

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
