### ISSUE TITLE
eMAG- Business Analyst (Internal App&amp Process Team) job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#24]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click on eMAG
4. Look for Business Analyst ( Internal App&amp Process Team) job

EXPECTED RESULTS:
city should be  București

ACTUAL RESULTS:
city displayed is Bucuresti-Sediul Central

**Comment by sebiboga** [comment]
fixed; @Ioana881 please retest

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
