### ISSUE TITLE
Quantrabbit - Night Shift Trading Operator job city is not displayed correctly

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_crawlers#3]
STEPS TO REPRODUCE:
1. access shaqodoon.ro
2. click on Companii
3. scroll and click on Quantrabbit
4. look for Night Shift Trading Operator job

EXPECTED RESULT:
city should be Cluj-Napoca.

ACTUAL RESULT:
city displayed is Cluj.

**Comment by sebiboga** [comment]
@tonisfr  fixed with previous bug; please retest. if happy, please CLOSE it
