### ISSUE TITLE
Microfocus-Communications-Business-Partner

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#34]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click on Microfocus 
4. Look for Communications-Business-Partner job

EXPECTED RESULTS:
city should be  București

ACTUAL RESULTS:
city displayed is Bucharest''

**Comment by sebiboga** [comment]
fixed; please retest @Ioana881

**Comment by Ioana881** [comment]
This job position is not available anymore.
closing the bug
