### ISSUE TITLE
Microfocus- Global Mobility Manager job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#35]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click on Microfocus
4. Look for Global Mobility Manager job

EXPECTED RESULTS:
city should be  București

ACTUAL RESULTS:
city displayed is Bucharest''

**Comment by sebiboga** [comment]
fixed; @Ioana881 please retest

**Comment by Ioana881** [comment]
This job position is not available anymore.
closing the bug
