### ISSUE TITLE
Quantrabbit -Customer Support Agent job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#4]
STEPS TO REPRODUCE:

1. acces shaqodoon.ro
2. click on Companii
3. scroll and click Quantrabbit
4. look for Customer Support Agent job
 
EXPECTED RESULT:

city should be Cluj-Napoca  

ACTUAL RESULT: 

city displayed is Cluj.

**Comment by sebiboga** [comment]
@Ioana881 fixed with previous bug; please retest. if happy, please CLOSE it

**Comment by sebiboga** [comment]
ENVIRONMENT:  PROD
  URL: https://shaqodoon.ro/
  browser: Chrome

STEPS TO REPRODUCE:
  1)  open URL in browser
  2)  click on Companii
  3)  scroll and click Quantrabbit
  4) look for Customer Support Agent job

EXPECTED RESULTS:
   city should be Cluj-Napoca

ACTUAL RESULTS:
   city displayed is Cluj.

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
