### ISSUE TITLE
Name of the company ING not dispalyed correctly

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_crawlers#40]
ENVIRONMENT: PROD
 URL: https://shaqodoon.ro/companii
 browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. search ING company card
 
EXPECTED RESULTS:
the company should be written ING with capitals

ACTUAL RESULTS:
the company is written Ing

**Comment by sebiboga** [comment]
fixed; @tonisfr please retest

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
