### ISSUE TITLE
Leroy Merlin - Product Marketing Specialist job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#51]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click on Leroy Merlin
4. Look for Product Marketing Specialist job

EXPECTED RESULTS:
city should be București

ACTUAL RESULTS:
city displayed is București Sediu

**Comment by sebiboga** [comment]
fixed;
