### ISSUE TITLE
Leroy Merlin- Responsabil Proces Supply Chain job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#52]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click on Leroy Merlin
4. Look for Responsabil Proces Supply Chain job

EXPECTED RESULTS:
city should be București

ACTUAL RESULTS:
city displayed is București Sediu

**Comment by sebiboga** [comment]
fixed;
