### ISSUE TITLE
Quantrabbit -Application Support-Linux Analyst job city is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#6]
STEPS TO REPRODUCE:
1. access shaqodoon.ro
2. click on Companii
3. scroll and click Quantrabbit
4. look for Application Support-Linux Analyst job
    
EXPECTED RESULT:
city should be Cluj-Napoca

ACTUAL RESULT:
city displayed is Cluj

**Comment by sebiboga** [comment]
@Ioana881 fixed with previous bug; please retest. if happy, please CLOSE it

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug

**Comment by Ioana881** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
