### ISSUE TITLE
iWelcome-null job country is not displayed correctly

### ISSUE THREAD

**Issue by Ioana881** [sebiboga/shaqo_doon_crawlers#69]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on Companii
3. Scroll and click in iWelcome
4. Look for null job 

EXPECTED RESULTS:
country should be România 

ACTUAL RESULTS:
country displayed is Romania

**Comment by sebiboga** [comment]
@Ioana881 I hope there is a bug for the name called "null"; it's not a valid title name
