### ISSUE TITLE
RIA Solutions Group not displayed correctly

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_crawlers#70]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. click on Companii
 3. scroll and look for Ria Solutions Group

EXPECTED RESULTS:
the company should be displayed RIA Solutions Group

ACTUAL RESULTS:
the company displayed is Ria Solutions Group

**Comment by sebiboga** [comment]
fixed; @tonisfr please retest

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
