### ISSUE TITLE
UTILBEN company is not displayed correctly

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_crawlers#82]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. click on Companii
 3. scroll and look for UTILBEN

EXPECTED RESULTS:
the company should be displayed UTILBEN

ACTUAL RESULTS:
the company displayed is Utilben

**Comment by sebiboga** [comment]
fixed;

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
