### ISSUE TITLE
3Pillar Global company is not displayed correctly

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_crawlers#89]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. click on Companii
 3. scroll and look for 3Pillar Global

EXPECTED RESULTS:
the company should be displayed 3Pillar Global

ACTUAL RESULTS:
the company displayed is 3 Pillar Global

**Comment by sebiboga** [comment]
nice; fixed;

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
