### ISSUE TITLE
IT Infrastucture Solutions Architect [Storage & SA... from Orange doesn't exist

### ISSUE THREAD

**Issue by tonisfr** [sebiboga/shaqo_doon_crawlers#92]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPTS TO REPRODUCE:
1. open URL in browser
2. click on Companii
3. scroll and click on Orange
4. look for IT Infrastucture Solutions Architect [Storage & SA... job
5. click on Detalii

EXPECTED RESULTS:
should be redirected to IT Infrastucture Solutions Architect [Storage & SA... job page

ACTUAL RESULTS:
IT Infrastucture Solutions Architect [Storage & SA... job is not available

**Comment by sebiboga** [comment]
nice spot; yes. we need to run the script every day. working on it.

**Comment by tonisfr** [comment]
Orange has multiple bugs with the same issue. Please take a look at the crawler @sebiboga.
